content_type:
  html:  text/html; charset=UTF-8
  rss:   application/rss+xml; charset=UTF-8
  xml:   text/xml; charset=UTF-8 
  jsonp: application/javascript; charset=UTF-8
  ics:   text/calendar; charset=UTF-8
externals:
  unc:    http://slice.unc.edu/index.php/events/all/eventlist?format=feed&type=rss
  ncsu:   http://calendar.activedatax.com/ncstate/RSSSyndicator.aspx?category=2-0&location=&type=N&binary=Y&keywords=
  nccu:   http://webevent.nccu.edu/RSSSyndicator.aspx?category=&location=&type=N&binary=Y
  dida:   http://eflyer.duke.edu/feed/index.php?display_id=2
  eflyer: http://eflyer.duke.edu/feed/
skins:
  calendar:
    rss:   rss
    html:  default
    xml:   feed
    jsonp: json-cal-src
  list: 
    rss:   rss-agg-list
    xml:   feed-list
    jsonp: json-list-src
suites:
  primary: 
    url: cal
    cal: calendar # initial feed route segment
    list: list # initial feed route segment
  secondary:
    url: student
    cal: buzz_calendar # initial feed route segment
    list: buzz_list # initial feed route segment
